### ISSUE TITLE
qna/famili100.txt not found

### ISSUE THREAD

**Issue by baqirhabsyi** [yulrizka/fam100#9]
Hi,

I saw the bot isn't running anymore and I'm trying to run the bot on my own for my group. I've installed the prerequisites, and when I tried to run the project, I got this error.

```
[I] 2020-04-22T06:26:17Z main.go:110: Fam100 STARTED version= buildtime=
[I] 2020-04-22T06:26:17Z main.go:111: Params quorum=3
[I] 2020-04-22T06:26:17Z main.go:130: loading question DB path=qna/famili100.txt
[F] 2020-04-22T06:26:17Z main.go:134: Failed loading question DB path=qna/famili100.txt error=failed to open "qna/famili100.txt": open qna/famili100.txt: no such file or directory stacktrace=goroutine 1 [running]:
github.com/uber-go/zap.takeStacktrace(0xc0000a3800, 0x400, 0x400, 0x0, 0x27, 0xc000029bc0)
	/home/ec2-user/go/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/stacktrace.go:39 +0xc7
github.com/uber-go/zap.Stack(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ec2-user/go/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/field.go:155 +0xa9
github.com/uber-go/zap.AddStacks.func1(0xc000061bc0, 0x0, 0x0)
	/home/ec2-user/go/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/hook.go:89 +0x67
github.com/uber-go/zap.(*logger).log(0xc0001d2480, 0x4, 0x917e80, 0x1a, 0xc000136500, 0x2, 0x2)
	/home/ec2-user/go/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/logger.go:136 +0x1a2
github.com/uber-go/zap.(*logger).Fatal(0xc0001d2480, 0x917e80, 0x1a, 0xc000136500, 0x2, 0x2)
	/home/ec2-user/go/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/logger.go:114 +0x65
main.main()
	/home/ec2-user/fam100/fam100/cmd/telegram/main.go:134 +0x1167
```

I checked the `qna` folder and the questions is not there. @yulrizka if you have the question saved somewhere, is it ok to share it to the ones who wants to run the bot again? Thanks in advance.

**Comment by yulrizka** [comment]
It's on a private repo. For any one that wishes to run the bot can pm me and I'll sent an invitate
